create table Person
(
    id    int generated by default as identity primary key,
    name  varchar not null,
    age   int not null check ( age > 0 ),
    email varchar not null unique
);

insert into Person(name, age, email)
values ('Tom', 15, 'tom@mail.ru');
insert into Person(name, age, email)
values ('Kristian', 23, 'kristian@internet.kz');
insert into Person(name, age, email)
values ('Layla', 16, 'layla@inbox.ru');
insert into Person(name, age, email)
values ('Victor', 31, 'victor@gmail.com');