create table director
(
    id   int generated by default as identity primary key,
    name varchar(100) not null,
    age  int check ( age > 0 )
);

INSERT INTO Director(name, age)
VALUES ('Quentin Tarantino', 57);
INSERT INTO Director(name, age)
VALUES ('Martin Scorsese', 78);
INSERT INTO Director(name, age)
VALUES ('Guy Ritchie', 52);
INSERT INTO Director(name, age)
VALUES ('Woody Allen', 85);
INSERT INTO Director(name, age)
VALUES ('David Lynch', 74);
INSERT INTO Director(name, age)
VALUES ('Christopher Nolan', 50);

create table movie
(
    id                 int generated by default as identity primary key,
    director_id        int references director (id),
    name               varchar(200) not null,
    year_of_production int check ( year_of_production > 1900 )
);

INSERT INTO Movie(director_id, name, year_of_production)
VALUES (1, 'Reservoir Dogs', 1992);
INSERT INTO Movie(director_id, name, year_of_production)
VALUES (1, 'Pulp Fiction', 1994);
INSERT INTO Movie(director_id, name, year_of_production)
VALUES (1, 'The Hateful Eight', 2015);
INSERT INTO Movie(director_id, name, year_of_production)
VALUES (1, 'Once Upon a Time in Hollywood', 2019);
INSERT INTO Movie(director_id, name, year_of_production)
VALUES (2, 'Taxi Driver', 1976);
INSERT INTO Movie(director_id, name, year_of_production)
VALUES (2, 'Goodfellas', 1990);
INSERT INTO Movie(director_id, name, year_of_production)
VALUES (2, 'The Wolf of Wall Street', 2013);
INSERT INTO Movie(director_id, name, year_of_production)
VALUES (3, 'Lock, Stock and Two Smoking Barrels', 1998);
INSERT INTO Movie(director_id, name, year_of_production)
VALUES (3, 'Snatch', 2000);
INSERT INTO Movie(director_id, name, year_of_production)
VALUES (4, 'Midnight in Paris', 2011);
INSERT INTO Movie(director_id, name, year_of_production)
VALUES (6, 'Inception', 2010);

select *
from director
         left join movie on director.id = movie.director_id;

create table citizen
(
    id   int generated by default as identity primary key,
    name varchar(100) not null,
    age  int check ( age > 0 )
);

INSERT INTO Citizen(name, age)
VALUES ('Bob', 12);
INSERT INTO Citizen(name, age)
VALUES ('Tom', 24);
INSERT INTO Citizen(name, age)
VALUES ('Katy', 39);
INSERT INTO Citizen(name, age)
VALUES ('Alice', 45);

create table passport
(
    citizen_id int references citizen (id) primary key,
    number     int not null
);

INSERT INTO Passport(citizen_id, number)
VALUES (1, 12345);
INSERT INTO Passport(citizen_id, number)
VALUES (2, 75124);
INSERT INTO Passport(citizen_id, number)
VALUES (3, 91245);
INSERT INTO Passport(citizen_id, number)
VALUES (4, 19259);

select *
from citizen
         left join passport on citizen.id = passport.citizen_id;

create table actor
(
    id   int generated by default as identity primary key,
    name varchar(100) not null,
    age  int check ( age > 0 )
);

INSERT INTO Actor(name, age)
VALUES ('Harvey Keitel', 81);
INSERT INTO Actor(name, age)
VALUES ('Robert De Niro', 77);
INSERT INTO Actor(name, age)
VALUES ('Leonardo DiCaprio', 46);
INSERT INTO Actor(name, age)
VALUES ('Jason Statham', 53);
INSERT INTO Actor(name, age)
VALUES ('Joe Pesci', 77);
INSERT INTO Actor(name, age)
VALUES ('Samuel L. Jackson', 72);

create table actor_movie
(
    actor_id int references actor (id),
    movie_id int references movie (id)
);

INSERT INTO Actor_Movie
VALUES (1, 1);
INSERT INTO Actor_Movie
VALUES (1, 2);
INSERT INTO Actor_Movie
VALUES (2, 5);
INSERT INTO Actor_Movie
VALUES (2, 6);
INSERT INTO Actor_Movie
VALUES (3, 4);
INSERT INTO Actor_Movie
VALUES (3, 7);
INSERT INTO Actor_Movie
VALUES (3, 11);
INSERT INTO Actor_Movie
VALUES (4, 8);
INSERT INTO Actor_Movie
VALUES (4, 9);
INSERT INTO Actor_Movie
VALUES (5, 6);
INSERT INTO Actor_Movie
VALUES (6, 2);
INSERT INTO Actor_Movie
VALUES (6, 3);

select *
from actor
         join actor_movie on actor.id = actor_movie.actor_id
         join movie on actor_movie.movie_id = movie.id;