drop table person;
drop sequence person_id_seq;


create table person (
    id int primary key generated by default as identity,
    name varchar(100) not null,
    age int check ( age between 0 and 200 )
);

insert into person(name, age) values ('Tom', 35);
insert into person(name, age) values ('Bob', 52);
insert into person(name, age) values ('Katy', 14);


create table item (
    id int primary key generated by default as identity,
    name varchar not null,
    person_id int references person(id) on delete set null
);

insert into item(person_id, name) values (1, 'Book');
insert into item(person_id, name) values (1, 'AirPods');
insert into item(person_id, name) values (2, 'Iphone');
insert into item(person_id, name) values (3, 'Kindle');
insert into item(person_id, name) values (3, 'TV');
insert into item(person_id, name) values (3, 'PlayStation');